name: tredo
description: "Test app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  dio: ^5.6.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1

  flutter_svg: ^2.0.9
  freezed_annotation:

  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  l: ^4.0.2
  loader_overlay: ^3.0.0
  lottie: ^2.7.0
  dotted_line: ^3.2.2
  mask_text_input_formatter: ^2.7.0
  package_info_plus: ^8.0.2
  path: ^1.8.2
  path_provider: ^2.1.1
  platform_info: ^4.0.2
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  pull_to_refresh: ^2.0.0
  pure: ^0.3.0
  rxdart: ^0.27.7
  select_annotation: ^0.2.0
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  stack_trace: ^1.10.0
  stream_bloc: ^0.5.3
  url_launcher: ^6.1.14
  modal_bottom_sheet: ^3.0.0
  http: ^0.13.6
  pinput: ^5.0.0
  direct_caller_sim_choice: ^1.0.5
  share_plus: ^10.0.0
  internet_connection_checker: ^1.0.0+1
  dots_indicator: ^3.0.0
  animated_snack_bar: ^0.4.0
  fluttertoast: ^8.2.8
  permission_handler: ^11.4.0
  flutter_local_notifications: ^18.0.1
  loading_animation_widget: ^1.3.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.5.0
  equatable: ^2.0.7
  firebase_core: ^3.12.0
  flutter_swipe_button: ^2.1.3
  cloud_firestore: ^5.6.6
  meta: ^1.15.0
  firebase_messaging: ^15.2.5
  dart_jsonwebtoken: ^2.17.0
  crypto: ^3.0.6


dependency_overrides:
  http: ^0.13.4

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  lint: ^2.2.0

flutter_gen:
  output: lib/src/core/gen
  integrations:
    flutter_svg: true
    # flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/service_account.json

  fonts:
    - family: Caption
      fonts:
        - asset: assets/fonts/caption/PTSansCaption-Bold.ttf
        - asset: assets/fonts/caption/PTSansCaption-Regular.ttf

    - family: Preahvihear
      fonts:
        - asset: assets/fonts/Preahvihear/Preahvihear-Regular.ttf
